name: Docker Build and Push

on:
  release:
    types: [published]

env:
  CUSTOM_IMAGE_NAME: pippo

jobs:
  docker:
    runs-on: ubuntu-22.04
    if: github.event.release.target_commitish == 'develop'
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Custom Image Name
        id: image_name
        run: |
            # Base image name
            BASE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{env.CUSTOM_IMAGE_NAME}}-test
            # Crea i tag
            TAGS="$BASE_NAME:${{ github.event.release.tag_name }}"
            echo "tags=$(echo $TAGS | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
            echo "tags=$(echo $TAGS | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
            echo "Generated tags: ${TAGS}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # tags: ${{ steps.image_name.outputs.tags }}
          tags: ${{ env.TAGS }}
      
      - name: Echo latest image and tags
        run: echo "Latest image and tags: ${{ env.TAGS }}"